# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d099d7dd649b3875dfb6983350553539ec39161c2d1d1c2fd5d2527d4d036a76d2f434bf955987b5149e2fa212a6f373d2ca6aaa3f37ac096049ab2282131508

test:
  secret_key_base: 4fd7778bedb7d5e4eba797371b0e8acb4b6ae2cefcf2f0c75554ab99294acd9418bb1b75c0560d09415665e4052a28b663040523335206666f001c1692d91a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
